---
- hosts: bein.link
  tasks:
      - name: update code
        git:
            repo: "/home/che/paste.git"
            dest: "/home/jail/foo/usr/local/www/paste"
        become: yes
        notify: restart

- hosts: foo@bein.link
  become: yes
  handlers:
      - name: restart uwsgi
        listen: restart
        service:
            name: uwsgi
            state: restarted
            arguments:
                - "paste"
        become: yes
