---
- hosts: all
  become: yes
  tasks:
      - name: update code
        git:
            repo: "/home/che/paste.git"
            dest: "{{ jails_dir }}/{{ jail }}/{{ jail_prefix }}/www/paste"
        when: inventory_hostname == "bein.link"
        notify: restart uwsgi
        vars:
            jail: "foo"
            jails_dir: "/home/jail"
            jail_prefix: "/usr/local"

  handlers:
      - name: restart uwsgi
        delegate_to: foo@bein.link
        service:
            name: uwsgi
            state: restarted
            # arguments:
            #     - "paste"
