---
- hosts: all
  become: yes
  tasks:
      - name: update code
        git:
            repo: "/home/che/paste.git"
            dest: "/home/jail/foo/usr/local/www/paste"
        when: inventory_hostname == "bein.link"
        notify: restart uwsgi

  handlers:
      - name: restart uwsgi
        delegate_to: foo@bein.link
        service:
            name: uwsgi
            state: restarted
            # arguments:
            #     - "paste"
